# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	increment_build_number
  	sync_code_signing
  	disable_automatic_code_signing(path: "AutoDeloyApp.xcodeproj")
    build_app(
    	scheme: "AutoDeloyApp",
    	export_method: "app-store",
    	export_options: {
      		provisioningProfiles: { 
        		"io.wumbo.AutoDeloyApp" => "match AppStore io.wumbo.AutoDeloyApp"
      		}
    	}
    )
    enable_automatic_code_signing(path: "AutoDeloyApp.xcodeproj")
    # upload_to_testflight
    pilot(skip_waiting_for_build_processing: false)
  end
end
